# Generated by Django 3.2.4 on 2021-06-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleOwned', models.CharField(max_length=100)),
                ('ownername', models.CharField(max_length=100)),
                ('ownerAddress', models.CharField(max_length=100)),
                ('vehicle_price', models.IntegerField()),
            ],
        ),
    ]
